### ISSUE TITLE
nsenter file is not available

### ISSUE THREAD

**Issue by ajeet-rock1** [tennix/ansible-k8s#3]
Hi Tennix,

If ia m following your step, i am not able to deploy cluster because not able find nsenter file in resource/bin/ folder.

Can you please check below error.

FAILED! => {"changed": false, "msg": "Could not find or access '/home/ubuntu/ansible-k8s/resources/bin/nsenter'"}

**Comment by tennix** [comment]
@Ajeet-rock1 I'm sorry, but this repo is not maintained anymore. You can use [kubespray](https://github.com/kubernetes-incubator/kubespray) to deploy a production K8s cluster.

**Comment by ajeet-rock1** [comment]
@tennix Thanks for your confirmation:)
