### ISSUE TITLE
etcd/tasks/net-install.yml 'item' is undefined"

### ISSUE THREAD

**Issue by clement10601** [tennix/ansible-k8s#4]
Err msg:
{"msg": "The task includes an option with an undefined variable. The error was: 'item' is undefined\n\nThe error appears to have been in '/home/kcw/ansible/ansible-k8s/roles/etcd/tasks/net-install.yml': line 13, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Copy etcd binary to bin path\n  ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'item' is undefined"}

Where can I find the item list and put a with_items parameter to correct this problem?

**Comment by tennix** [comment]
@clement10601 I'm sorry, this repo is not maintained anymore. You can try [kubespray](https://github.com/kubernetes-incubator/kubespray) to deploy a production K8s cluster.
